# Generated by Django 4.1.2 on 2022-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie')),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
